logging:
    level:
        ROOT: INFO
        org: INFO
        com.vk.spring: INFO
spring:
    application:
        name: spring-boot-jpa
    jmx:
        enabled: false
    messages:
        basename: i18n/messages
    main:
        allow-bean-definition-overriding: true
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
server:
    servlet:
        session:
            cookie:
                http-only: true
    port: 8080
